name: coolappflutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
# version: 1.8.5+50

version: 1.15.0+64

environment:
  sdk: ">=3.3.4 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  image_cropper: ^9.1.0
  zego_uikit_prebuilt_video_conference: ^2.9.6
  flutter_typeahead: ^5.2.0
  cupertino_icons: ^1.0.6
  syncfusion_flutter_pdf: ^28.1.39
  # advance_pdf_viewer2: ^2.0.5+1
  app_links: ^6.3.2
  audio_video_progress_bar: ^2.0.1
  audioplayers: ^6.1.0
  cached_network_image: ^3.3.1
  camera: ^0.11.0+2
  change_app_package_name: ^1.1.0
  clipboard: ^0.1.3
  custom_refresh_indicator: ^4.0.1
  # appinio_social_share: ^0.2.6
  decimal: ^3.0.2
  device_info_plus: ^11.2.1
  dio: ^5.5.0+1
  #  firebase_analytics: ^10.8.6
  # firebase_core: ^2.25.4
  firebase_crashlytics: ^4.3.0
  flutter_dotenv: ^5.1.0
  # flutter_file_downloader: ^2.0.0
  flutter_inappwebview: ^6.1.5
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  # flutter_share_me:
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.9
  flutter_tts: ^4.2.2
  flutter_widget_from_html: ^0.16.0
  http_parser: ^4.0.2
  image_picker: ^1.0.7
  infinite_scroll_pagination: ^5.0.0
  intl: any
  intl_phone_field: ^3.2.0
  mobile_scanner: ^6.0.2
  modal_progress_hud_nsn: ^0.5.1
  music_visualizer: ^1.0.4
  open_filex: ^4.4.0
  package_info_plus: ^8.1.3
  path_provider: ^2.0.11
  percent_indicator: ^4.2.3
  permission_handler: ^11.2.0
  phone_form_field: ^10.0.3
  pin_code_text_field: ^1.8.0
  pretty_dio_logger: ^1.3.1
  provider: ^6.1.1
  record: ^5.0.5
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  syncfusion_flutter_pdfviewer: ^28.1.39
  timeago: ^3.6.1
  url_launcher: ^6.2.4
  video_compress: ^3.1.3
  video_player: ^2.8.1
  dio_http2_adapter: ^2.5.3
  # uni_links: ^0.5.1
  intl_utils: ^2.5.0
  flutter_image_compress: ^2.4.0
  android_intent_plus: ^5.2.2
  get_thumbnail_video: ^0.7.3
  # video_thumbnail: ^0.5.0
  firebase_messaging: ^15.2.0
  firebase_core: ^3.10.0
  flutter_downloader: ^1.10.1
  flutter_html:
  dropdown_search: ^6.0.1
  google_maps_flutter: ^2.4.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_screenutil: ^5.9.3
  flutter_sound: ^9.2.13

  faker: ^2.1.0
  # file_picker: ^8.0.3
  firebase_auth: ^5.0.0
  # firebase_core: ^3.0.0
  firebase_storage: ^12.0.0

  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.14
  flutter_firebase_chat_core: ^1.6.8
  flutter_rating_bar: ^4.0.1
  qr_code_scanner_plus: ^2.0.10+1
  qr_flutter: ^4.1.0
  share_plus: ^10.1.4

  # image_picker: ^1.1.2
  mime: ^2.0.0
  # open_filex: ^4.4.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter

dependency_overrides:
  file_picker:
    git:
      url: https://github.com/abdelaziz-mahdy/flutter_file_picker
      ref: fix-flutter-3.27-compile-error

flutter_lints: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/cool_app.png"

flutter:
  uses-material-design: true

  assets:
    # - .env.prod
    # - .env.dev
    - images/
    - images/promo/
    - images/konsultasi/
    - images/menu/
    - assets/images/
    - assets/icons/
    - images/qrcode/
    - images/buku/
    - images/brain/
    - images/chat/
    - images/profiling/
    - assets/audio/1717485918_Cool Compas - Master_2.wav

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
flutter_intl:
  main_locale: en_US
  enabled: true
  generate: true
# flutter_intl:
#   enabled: true
#   generate: true
#   localizations_directories:
#     - lib/l10n
