name: cool_app
description: "A new Flutter project."
publish_to: "none"
version: 1.5.3+38

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  advance_pdf_viewer_fork: ^2.0.0
  app_links: ^6.1.4
  audio_video_progress_bar: ^2.0.1
  audioplayers: ^5.2.1
  cached_network_image: ^3.3.1
  camera: ^0.9.4+5
  change_app_package_name: ^1.1.0
  clipboard: ^0.1.3
  custom_refresh_indicator: ^3.0.0
  # appinio_social_share: ^0.2.6
  decimal: ^2.3.3
  device_info_plus: ^9.0.0
  dio: ^5.5.0+1
  #  firebase_analytics: ^10.8.6
  firebase_core: ^2.25.4
  firebase_crashlytics: ^3.4.18
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  # flutter_file_downloader: ^2.0.0
  flutter_inappwebview: ^5.8.0
  flutter_local_notifications: ^16.3.2
  flutter_localizations:
    sdk: flutter
  flutter_share_me: ^1.4.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.9
  flutter_tts: ^3.8.5
  flutter_widget_from_html: ^0.14.11
  http_parser: ^4.0.2
  image_picker: ^1.0.7
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.18.1
  intl_phone_field: ^3.2.0
  mobile_scanner: ^3.4.1
  modal_progress_hud_nsn: ^0.5.1
  music_visualizer: ^1.0.4
  open_filex: ^4.4.0
  package_info_plus: ^5.0.1
  path_provider: ^2.0.11
  percent_indicator: ^4.2.3
  permission_handler: ^11.2.0
  phone_form_field: ^9.1.0
  pin_code_text_field: ^1.8.0
  pretty_dio_logger: ^1.3.1
  provider: ^6.1.1
  record: ^5.0.5
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  syncfusion_flutter_pdfviewer: ^23.2.6
  timeago: ^3.6.1
  url_launcher: ^6.2.4
  video_compress: ^3.1.2
  video_player: ^2.8.1
  dio_http2_adapter: ^2.5.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/cool_app.png"

flutter:
  uses-material-design: true

  assets:
    # - .env.prod
    # - .env.dev
    - images/
    - images/menu/
    - assets/images/
    - assets/icons/
    - images/buku/
    - images/brain/
    - images/chat/
    - assets/audio/1717485918_Cool Compas - Master_2.wav

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
flutter_intl:
  main_locale: en_US
  enabled: true
